
CXX = clang++
CC = clang++
CXXFLAGS = -Wall -Werror -std=c++11 -Ofast
LDFLAGS = -lm

.PHONY: default clean all

default: simulation


simulation: path-integral.o 

simulatio.o: path-integral.h warray.h

path-integral.o: path-integral.h




clean:
	rm -f *.o simulation

all: clean default
